### ISSUE TITLE
Problem building with Cabal

### ISSUE THREAD

**Issue by bjing** [dcSpark/fracada#9]
I have trouble compiling with `cabal build`.

The Plutus (https://github.com/input-output-hk/plutus) tag I'm on is `plutus-pab/v0.0.1`. I can start a `nix-shell` from within the Plutus repo checkout, no problem.

I've attached the build log for your review. 
[build.log](https://github.com/dcSpark/fracada/files/7611758/build.log)

Platform I'm on: 
OS: OSX Monterey. 
GHC: 8.10.7
Cabal: 3.6.2.0
Plutus checkout: plutus-pab/v0.0.1 (also tried plutus-pab/v0.0.2, same thing)

Can you offer me some insight how I can make this work?

**Comment by LeadPlutusDev** [comment]
The code has been upgraded to use pab 0.0.2 tag, and that might be the problem :) (I've updated the documentation to specify the correct version now)

**Comment by bjing** [comment]
@LeadPlutusDev thanks for getting back to me. I used that tag in my Plutus checkout and it's still the same.

Mind if I ask what versions of tools you used to successfully build this?
What I'm looking for:
* OS and version
* GHC
* Cabal

Thanks!

**Comment by bjing** [comment]
I've finally gotten it to build.

I did the following, not sure what combination of them did the traick:
* in ~/.cabal/config, disable `library-profiling` and `documentation`,
* remove `~/.cabal/packages/*` and `~/.cabal/store/*`
* under my local plutus repo checkout:
  ```
  nix build -f nix/default.nix docs
  nix build -f default.nix docs.site
  ```
